trainer:
  task: test_only
  seed: 2024
  num_devices: 1

# for Tensorboard logger
logger:
    save_dir: /root/tf-logs
    sub_dir: logs
    name: 50-way-top-1
    version: 0
    default_hp_metric: false

lightning:
  name: model.lightnings.LitEvaluationModel
  task: 
    name: n_way_top_k_acc
    params:
      n_way: 50
      num_trials: 40
      top_k: 1

  evaluation_model: &evaluation_model
    name: model.models.PytorchVisionModel
    pretrained_model_path: /root/autodl-tmp/pretrained/vit_h_14_swag-80465313

dataset: 
  name: data.dataset.GeneratedImageDataset
  num_workers: 2 # num_devices * 2
  batch_size: 1
  gt_image_ext: JPEG

  image_root_path: 
    test: pass
  
  gt_image_root_path: /root/autodl-tmp/data/eeg-imagenet/images

  evaluation_model: *evaluation_model





