trainer:
  task: train_only
  seed: 2024
  save_directory: /root/autodl-tmp/pretrained
  check_val_every_n_epoch: &interval 1
  max_epochs: 10
  num_devices: 1

  checkpoint:
    dirpath: /root/autodl-tmp/ckpts
    monitor: step
    filename: lit-{step}
    save_top_k: 1
    mode: max
    every_n_epochs: *interval
    save_last: false

# for Tensorboard logger
logger:
    save_dir: /root/tf-logs
    sub_dir: logs
    name: vision-adapter
    version: finetune
    default_hp_metric: false

lightning:
  name: model.lightnings.LitVisionAdapterModel
  diffusion_model_path: &diffusion_model_path /root/autodl-tmp/pretrained/stable-diffusion-v1-5
  pretrained_model_path: /root/autodl-tmp/pretrained/vision-adapter/part-1
  
  snr_gamma: 5.0
  num_images_per_prompt: 4
  num_inference_steps: 30

  condition_model:
    name: model.models.VisionModelWithProjection
    model_path: &condition_model_path /root/autodl-tmp/pretrained/clip-vit-large-patch14-336

model:
  diffusion_model_path: *diffusion_model_path

  projection_config:
    input_dim: 768
    num_tokens: 4

dataset: 
  name: data.dataset.ImageDataset
  num_workers: 2 # num_devices * 2
  resolution: 512
  batch_size: 8
  image_ext: JPEG

  image_root_path: 
    train: /root/autodl-tmp/data/eeg-imagenet/images
    val: /root/autodl-tmp/data/eeg-imagenet/val-images

  condition_model_path: *condition_model_path

  drop_probability: 0.05

# constant learning rate
optimizer:
  name: torch.optim.AdamW
  params:
    lr: 2.e-5
    weight_decay: 0.01
