trainer:
  seed: 2024
  resume_ckpt_path: null

# for Tensorboard logger
logger:
    save_dir: /root/tf-logs
    sub_dir: logs
    name: test-brain-adapter
    version: 5-95-1 # 5-95-i, i in [1, 2, 3, 4, 5, 6]
    default_hp_metric: false

lightning:
  name: model.lightnings.LitBrainAdapterModel
  pretrained_model_path: /root/autodl-tmp/pretrained/brain-adapter-moe # pretrained adapter model path
  diffusion_model_path: &diffusion_model_path /root/autodl-tmp/pretrained/stable-diffusion-v1-5

  snr_gamma: 5.0
  num_images_per_prompt: 4
  num_inference_steps: 50

  brain_model_path: /root/autodl-tmp/pretrained/brain-model-moe # brain encoder path

model: null


dataset: 
  name: data.dataset.EEGImageNetDatasetForReconstruction
  num_workers: 2 # num_devices * 4
  resolution: 512
  batch_size: 4
  image_ext: JPEG
  subject: 1 # 1, 2, 3, 4, 5, 6

  eeg_data_path: /root/autodl-tmp/data/eeg-imagenet/eeg_5_95_std.pth
  splitter_path: /root/autodl-tmp/data/eeg-imagenet/block_splits_by_image_single.pth # splitter for a single subject
  image_root_path: /root/autodl-tmp/data/eeg-imagenet/images

  clip_model_path: /root/autodl-tmp/pretrained/clip-vit-large-patch14-336
  diffusion_model_path: *diffusion_model_path

