trainer:
  task: train_and_test_with_last
  seed: 2024
  save_directory: /root/autodl-tmp/pretrained
  check_val_every_n_epoch: 1
  max_epochs: 2
  num_devices: 1

  checkpoint:
    dirpath: /root/autodl-tmp/ckpts
    monitor: step
    filename: lit-{step}
    save_top_k: 1
    mode: max
    every_n_epochs: 1
    save_last: true

# for Tensorboard logger
logger:
    save_dir: /root/tf-logs
    sub_dir: logs
    name: brain-adapter
    version: 5-95
    default_hp_metric: false

lightning:
  name: model.lightnings.LitBrainAdapterModel
  pretrained_model_path: /root/autodl-tmp/pretrained/vision-adapter/part-0
  diffusion_model_path: &diffusion_model_path /root/autodl-tmp/pretrained/stable-diffusion-v1-5

  snr_gamma: 5.0
  num_images_per_prompt: 4
  num_validation_images: 8
  num_inference_steps: 50

  brain_model_path: /root/autodl-tmp/pretrained/brain-model

model:
  projection_config:
    input_dim: 768
    num_tokens: 4


dataset: 
  name: data.dataset.EEGImageNetDatasetForReconstruction
  num_workers: 2 # num_devices * 4
  resolution: 512
  batch_size: 4
  image_ext: JPEG
  subject: 0

  eeg_data_path: /root/autodl-tmp/data/eeg-imagenet/eeg_5_95_std.pth
  splitter_path: /root/autodl-tmp/data/eeg-imagenet/block_splits_by_image_single.pth
  image_root_path: /root/autodl-tmp/data/eeg-imagenet/images
  diffusion_model_path: *diffusion_model_path

  merge_train_and_val: true

  drop_probability: 0.05

# constant learning rate
optimizer:
  name: torch.optim.AdamW
  params:
    lr: 2.e-5
    weight_decay: 0.01
