trainer:
  task: train_and_test_with_best
  seed: 2024
  save_directory: /root/autodl-tmp/pretrained
  check_val_every_n_epoch: &interval 1
  max_epochs: &max_epochs 30
  num_devices: 1

  checkpoint:
    dirpath: /root/autodl-tmp/ckpts
    monitor: val_loss
    filename: lit-{val_loss:.4f}
    save_top_k: 1
    mode: min
    every_n_epochs: *interval
    save_last: false

# for Tensorboard logger
logger:
    save_dir: /root/tf-logs
    sub_dir: logs
    name: brain-model-moe
    version: 5-95
    default_hp_metric: false

lightning:
  name: model.lightnings.LitBrainModel

  pretrained_model_path: null
  clip_model_path: &clip_model_path /root/autodl-tmp/pretrained/clip-vit-large-patch14-336

  log_clip_logits: true
  
  cls_ratio: 0.08
  

model:
  name: model.models.TransformerEncoderModel
  encoder_name: model.modules.EEGMOETransformer

  num_channels: 128
  num_subjects: 6
  num_samples: 440
  patch_size: 4
  hidden_size: 768
  num_layers: 8
  num_attention_heads: 12
  mlp_ratio: 1.0
  dropout: 0.5
  act_fn: gelu


dataset: 
  name: data.dataset.EEGImageNetFeaturesDataset

  num_workers: 2 # num_devices * 2
  subject: 0 # 0 means using data of all subjects
  batch_size: 64
  num_classes: 40

  image_ext: JPEG

  eeg_data_path: /root/autodl-tmp/data/eeg-imagenet/eeg_5_95_std.pth
  splitter_path: /root/autodl-tmp/data/eeg-imagenet/block_splits_by_image_all.pth
  image_embeds_path: image_embeds.pth

  merge_train_and_val: true


optimizer:
  name: torch.optim.AdamW
  params:
    lr: 1.e-4
    weight_decay: 0.05

scheduler:
  name: flash.core.optimizers.LinearWarmupCosineAnnealingLR
  params:
    warmup_epochs: 3
    max_epochs: *max_epochs
    warmup_start_lr: 4.e-5
    eta_min: 2.e-5
