trainer:
  seed: 2024
  check_val_every_n_epoch: 1
  max_epochs: 5
  num_devices: 1

  checkpoint:
    dirpath: checkpoints
    monitor: step
    filename: lit-{step}
    save_top_k: 5 # save all and conduct ablation studies
    mode: max
    every_n_epochs: 1
    save_last: false
  
  resume_ckpt_path: null

# for Tensorboard logger
logger:
    save_dir: all-logs
    sub_dir: logs
    name: brain-ip-adapter
    version: 5-95-train
    default_hp_metric: false

lightning:
  name: model.lightnings.LitBrainIPAdapterModel

  diffusion_model_path: &diffusion_model_path pretrained/stable-diffusion-v1-5

  snr_gamma: 5.0
  num_images_per_prompt: 4
  num_inference_steps: 50

  brain_model_path: pretrained/brain-model
  log_val_images: true

model: 
  ip_adapter_model_path: pretrained/ip-adapter-ada-4m/ip_adapter.bin
  projection_config: 
    input_dim: 768
    num_tokens: 4


dataset: 
  name: data.dataset.EEGImageNetDatasetForReconstructionWithText
  num_workers: 2 # num_devices * 4
  resolution: 512
  batch_size: 4
  image_ext: JPEG
  subject: 0 # MOE is trained on all subjects and there is no need to finetune on a single subject

  eeg_data_path: data/eeg-imagenet/eeg_5_95_std.pth
  splitter_path: data/eeg-imagenet/block_splits_by_image_all.pth
  image_root_path: data/eeg-imagenet/images

  clip_model_path: pretrained/clip-vit-large-patch14-336
  diffusion_model_path: *diffusion_model_path

  merge_train_and_val: true

  drop_probability: 0.05 # for enhancing classifier-free guidance

# constant learning rate
optimizer:
  name: torch.optim.AdamW
  params:
    lr: 2.e-5 # finetune
    weight_decay: 0.01
