trainer:
  task: train_and_test_with_best
  seed: 2024
  save_directory: /root/autodl-tmp/pretrained
  check_val_every_n_epoch: 1
  max_epochs: 30
  num_devices: 1

  checkpoint:
    dirpath: /root/autodl-tmp/ckpts
    monitor: val_loss
    filename: lit-{val_loss:.4f}
    save_top_k: 1
    mode: min
    every_n_epochs: 1
    save_last: false

# for Tensorboard logger
logger:
    save_dir: /root/tf-logs
    sub_dir: logs
    name: brain-vision-model
    version: 5-95
    default_hp_metric: false

lightning:
  name: model.lightnings.LitBrainStudentModel
  pretrained_model_path: null

model:
  eeg_config:
    encoder_name: model.modules.EEGTransformer

    num_channels: 128
    num_samples: 440
    patch_size: 4
    hidden_size: 768
    num_layers: 8
    num_attention_heads: 12
    mlp_ratio: 1.0
    dropout: 0.1

    projection_dim: 768


dataset: 
  name: data.dataset.EEGImageNetDataset

  num_workers: 4 # num_devices * 4
  subject: 0 # 0 means using data of all subjects
  batch_size: 4

  eeg_data_path: /root/autodl-tmp/data/eeg-imagenet/eeg_5_95_std.pth
  splitter_path: /root/autodl-tmp/data/eeg-imagenet/block_splits_by_image_all.pth
  teacher_embeds_path: /root/autodl-tmp/data/eeg-imagenet/embeds/clip-vit-l-14-text-embeds.bin

  merge_train_and_val: true


optimizer:
  name: torch.optim.AdamW
  params:
    lr: 1.e-4
    weight_decay: 0.05

scheduler:
  name: flash.core.optimizers.LinearWarmupCosineAnnealingLR
  params:
    warmup_epochs: 3
    max_epochs: 30
    warmup_start_lr: 5.e-5
    eta_min: 4.e-5
